apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 2 # You can specify the desired number of replicas here
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-container
        image: gautadas/javamavenwebapp:v1.0.0 # Replace with your Docker image name and tag (e.g., nginx:latest)
        ports:
        - containerPort: 80 # Replace with the port your application inside the container listens on
